### ISSUE TITLE
Shown destinations should depend on period, not location.

### ISSUE THREAD

**Issue by vukisoft** [stevenblair/commuter-bliss-uk#2]
It says: "If you are near your configured home station, you will be shown routes to your work station; otherwise you will be shown routes home"

I think latter is not correct behaviour, it should work like in the mornings it should always show trains to "work", and evening period to "home".
It would be useful for example if there are alterations and I have to change somewhere unexpectedly, so it will show trains to actual destination from that station. I think we can agree that commuters' destination in the mornings is always "work" and afternoons it's always "home" :)

**Comment by stevenblair** [comment]
I see what you mean. I've updated the app with this logic. Similar to what is done without GPS-based location enabled, the destination will be the work station before midday, and the home station otherwise.

**Comment by vukisoft** [comment]
I hope you still left the logic which helps me to my destination from whatever station I am, by location.

**Comment by stevenblair** [comment]
Yes, this will still happen if "use GPS location" is enabled in the configuration. In practice, this relies on the accuracy of your phone's location reporting - and so obviously won't work well in underground stations/platforms.
