### ISSUE TITLE
Leave last good date on screen if network drops

### ISSUE THREAD

**Issue by kramos** [stevenblair/commuter-bliss-uk#3]
Hi Steven
Great watch face, thanks for creating it.  For me when I come out of the underground station sometimes my phone doesn't get online quickly meaning the watch face has no train data.  I was wondering if it would be possible to have a mode where the watch continues displays the last known good data in the event of no network.  I must admit I tried looking in the code but was defeated.  If you could even give some pointers, I'd have a go!  Thanks again.

NB. this isn't an issue, I just don't seem to be able to label it properly.

**Comment by stevenblair** [comment]
Thanks very much. What _should_ happen is that you get a red dot in the top left corner which indicates that the previous network request failed - but the old train time data should remain on the watch (even if it shows "-10 mins" for the next train which already left). But there are a lot of edge cases so I'll do some testing and think about this.
