### ISSUE TITLE
Colour setting does not work.

### ISSUE THREAD

**Issue by vukisoft** [stevenblair/commuter-bliss-uk#5]
Trying to set clock colour, and whatever I do it just remains red.
I just changed from another (non-colour) watch to pebble time steel, but colour setting don't seem to be applied.

**Comment by vukisoft** [comment]
Looks like the reason is that it is not supported in the code at all :D Only the configuration exists, but not used .. Any plans to use it? .. Please? :D

**Comment by stevenblair** [comment]
Yes, that's a good point - sorry for the confusion. This has been implemented, but I'm still in the process of testing the updated app. I will hopefully finish this in the next few days.

**Comment by stevenblair** [comment]
I've updated the app quite substantially, which also happens to include the option to change the clock colour. Feel free to let me know if anything else doesn't work...

**Comment by vukisoft** [comment]
Awesome, thx!
