### ISSUE TITLE
Showing PAST trains, not upcoming

### ISSUE THREAD

**Issue by vukisoft** [stevenblair/commuter-bliss-uk#6]
Since the update I had the opportunity to see the trains for the first time and I realized that it shows the past trains, not upcoming. It looks like it gets the time wrong by minus 1 hour...
Example, at 7:00 it showed the next upcoming train as if it was 6:00 (except that is showed minus minutes). Pretty sure it's a timezone issue when sending the query to the network rail api.

**Comment by stevenblair** [comment]
I have noticed issues such as this occasionally, but not for a while. There is a bug in the Pebble JavaScript VM (which is beyond my control) which may be a factor. Could you try rebooting your phone to force the VM to restart?

**Comment by vukisoft** [comment]
Looks like it's okay after phone reboot, displaying correctly now.

**Comment by stevenblair** [comment]
That's good. The bug in the JavaScript VM basically means that it doesn't dynamically update the timezone - so this issue may pop up again if you change timezone.
